# Uncomment the next line to define a global platform for your project
# platform :ios, '13.0'

target 'liveApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  # 引入Moya基础库
  pod 'Moya', '~> 15.0'
  # Pods for liveApp

end
